# Generated by Django 3.2.5 on 2021-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_price_rage'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.IntegerField(choices=[(1, 'landmarks'), (2, 'food'), (3, 'bars')], default=2),
        ),
    ]
