# Generated by Django 3.2.5 on 2021-07-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.IntegerField(choices=[('landmarks', 'landmarks'), ('food', 'food'), ('bars', 'bars')], default=2),
        ),
    ]
