# Generated by Django 3.2.5 on 2021-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
