# Generated by Django 3.2.5 on 2021-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210721_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lattiude',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
